### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by jmgunter** [supabase-community/seed#189] opened 2024-07-31 14:27 UTC
A new installation of @snaplet/seed in my typescript project is now throwing this error when running ```npx tsx seed.ts```

```
TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.<anonymous> (/Users/xyz/Development/xyz/node_modules/fictional/hash.js:7:43)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.transformer (/Users/xyz/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DxMxtvGN.cjs:2:1122)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/xyz/Development/xyz/node_modules/fictional/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.transformer (/Users/xyz/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DxMxtvGN.cjs:2:1122)
```
    
    
My seed.ts file:
    
```

import { createSeedClient } from "@snaplet/seed";

require("dotenv").config({ path: "./.env.local" });

const main = async () => {
  const seed = await createSeedClient({ dryRun: true }); // Only log the queries that would be executed so we can use supabase's built in logging

// Doing some seeding here

  process.exit();
};

main();
```

**Comment by Aietes** [comment] 2024-07-31 15:23
I'm having a similar issue with a setup that worked just fine until now:

```shell
> npx tsx seed.ts

<project>/node_modules/.pnpm/fictional@2.0.2/node_modules/fictional/hash.js:7
var generateKey = siphash.string16_to_key.bind(siphash)
                                          ^

TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.<anonymous> (<project>/node_modules/.pnpm/fictional@2.0.2/node_modules/fictional/hash.js:7:43)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.transformer (/Users/xxx/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DxMxtvGN.cjs:2:1122)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (<project>/node_modules/.pnpm/fictional@2.0.2/node_modules/fictional/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.transformer (/Users/xxx/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/register-DxMxtvGN.cjs:2:1122)

Node.js v20.15.1
 ELIFECYCLE  Command failed with exit code 1.
```

This happens on import, even if I have nothing else in `seed.ts`. Just `import { createSeedClient } from '@snaplet/seed'` causes the error.

I rolled back the snaplet version, and even the entire project, but I always get this error. I'm baffled to why?

**Comment by camrun91** [comment] 2024-07-31 15:54
I am having the same issue and it has all worked until this morning. I wonder if it has something to do with Snaplet shutting down?

**Comment by josematute** [comment] 2024-07-31 16:02
Same issue here.

**Comment by Aietes** [comment] 2024-07-31 16:12
Since the error comes from the fictional package, I also opened an issue over there: https://github.com/oftherivier/fictional/issues/39

Since fictional didn't change most recently, I'm not sure why the error comes up now. Maybe it's ESM module related?

**Comment by gweese** [comment] 2024-07-31 17:50
Also having this issue. 
Currently using the Prisma adapter. Previously working seeding is now broken, and I also tried it with the default test user example and that is throwing this exact same error in OP.

**Comment by benjaminpreiss** [comment] 2024-07-31 19:04
Having a similar issue (reading 'trim')...

Fixed by using: `pnpm dlx @snaplet/seed@0.97.20 generate`

**Comment by jmgunter** [comment] 2024-08-01 05:29
For me the issue turned out to be the latest release of tsx. Running npx tsx@4.16.2 seed.ts works.

**Comment by CarelFdeWaal** [comment] 2024-08-01 06:58
Using latest tsx seems to solve the issue.

I tested with:
```
npx tsx --version
tsx v4.16.4
node v22.5.1
```
Will close issue soon if no more comment

**Comment by Aietes** [comment] 2024-08-01 07:24
On my side no luck, I'm still getting the same error, even using the latest tsx.

```shell
❯ npx tsx --version
tsx v4.16.4
node v22.4.1
```

**Comment by Aietes** [comment] 2024-08-02 10:26
The upstream issue has been solved, things should work again without a workaround.

I had to reinstall all modules with `pnpm` after deleting the lock file and the `node_modules` folder to ensure the version of `fictional` that fixes the issue is in the dependencies.

**Closed** 2024-08-31 04:32 UTC
